config/routes.rb
Tickets::Application.routes.draw do
  devise_for :users
  resources :ticket_items

  resources :users

  get '/home'                          => 'pages#home'
  get '/mines'             => 'ticket_items#mines'

   root 'pages#home'

end

app/models/ticket_item.rb
class TicketItem < ActiveRecord::Base
  belongs_to :user 
  accepts_nested_attributes_for :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ticket_items, :foreign_key => :user_id 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def home
   @ticket_item = TicketItem.new
  end

  def about
  end

  def contact
  end
end

app/controllers/ticket_items_controller.rb
class TicketItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket_item, only: [:show, :edit, :update, :destroy]

  # GET /ticket_items
  # GET /ticket_items.json
  def index
    @ticket_items = TicketItem.all
  end

  # GET /ticket_items/1
  # GET /ticket_items/1.json
  def show
  end

  def mines
  @ticket_items = TicketItem.where("user_id = ?", current_user.id)
  render action: "index", collection: @ticket_items
  end


  # GET /ticket_items/new
  def new
    @ticket_item = TicketItem.new
    @ticket_item.user = current_user
  end

  # GET /ticket_items/1/edit
  def edit
    @ticket_items = TicketItem.where("id = ?", :id).includes( :user )
  end

  # POST /ticket_items
  # POST /ticket_items.json
  def create
  @ticket_item = TicketItem.new
#   @post.number = params[:post][:number].gsub(/,/,'.').to_f # => 12.13
   
    @ticket_item.created_on = Time.new
    @ticket_item.user = current_user
    @ticket_item.user_id = current_user.id
  
    #@ticket_item = TicketItem.new(ticket_item)

#    @ticket_item = TicketItem.new(ticket_item_params)


    respond_to do |format|
      if @ticket_item.save
        flash[:id] = "Created ticket with id:" + @ticket_item.id.to_s
        format.html { redirect_to @ticket_item, notice: 'Ticket item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ticket_item }
        format.xml { render xml: @ticket_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @ticket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_items/1
  # PATCH/PUT /ticket_items/1.json
  def update
  @submitval = params[:commit]
  if @submitval == "Close"
   @ticket_item.finished_on = Time.new
  elsif @submitval == "Assign to me"
   @ticket_item.assigned_on = Time.new
  end
  
    respond_to do |format|
      if @ticket_item.update(ticket_item_params)
        format.html { redirect_to @ticket_item, notice: 'Ticket item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ticket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_items/1
  # DELETE /ticket_items/1.json
  def destroy
    @ticket_item.destroy
    respond_to do |format|
      format.html { redirect_to ticket_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_item
      @ticket_item = TicketItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_item_params
      params.require(:ticket_item).permit(:name, :created_on, :assigned_on, :description, :user_id, :street, :city, :state, :zipcode, :mainstreet, :crossingstreet, :intersectionnum, :btnSubmit)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ticket_items_helper.rb
module TicketItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div>
Footer here
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
<li>
	<% if user_signed_in? %>
	  Logged in as <strong><%= current_user.email %></strong>.
	  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
	  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
	  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
</li>	
  <li><%= link_to 'Log new calls', root_path %></li>
  <li><%= link_to 'My tickets' , mines_path %></li>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Trouble Calls" %></title>
 
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css"/>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Tickets" %>">
           <script src="http://code.jquery.com/jquery-2.1.0.min.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.3/jquery-ui.min.js" type="text/javascript"></script>

    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/additional-methods.min.js" type="text/javascript"></script>

    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
    <!--  <%= notice %> //-->
      <%= alert %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
    <footer>
    <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<%= form_for @ticket_item do |f| %>
<input type="Submit" value="Log Call" style="width:200px;height:100px;color:white;font-size:20px;background-color:gray;" />
<% end %>

app/views/ticket_items/_form.html.erb
<%= form_for(@ticket_item) do |f| %>
  <% if @ticket_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket_item.errors.count, "error") %> prohibited this ticket_item from being saved:</h2>

      <ul>
      <% @ticket_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :created_on %><br>
    <%= f.date_select :created_on %>
  </div>
  <div class="field">
    <%= f.label :assigned_on %><br>
    <%= f.date_select :assigned_on %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ticket_items/edit.html.erb
<h1>Editing ticket_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket_item %> |
<%= link_to 'Back', ticket_items_path %>

app/views/ticket_items/index.html.erb
<h1>Listing ticket_items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Created on</th>
      <th>Assigned on</th>
      <th>Description</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_items.each do |ticket_item| %>
      <tr>
        <td><%= ticket_item.name %></td>
        <td><%= ticket_item.created_on %></td>
        <td><%= ticket_item.assigned_on %></td>
        <td><%= ticket_item.description %></td>
        <td><%= ticket_item.user_id %></td>
        <td><%= link_to 'Show', ticket_item %></td>
        <td><%= link_to 'Edit', edit_ticket_item_path(ticket_item) %></td>
        <td><%= link_to 'Destroy', ticket_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket item', new_ticket_item_path %>

app/views/ticket_items/new.html.erb
<h1>New ticket_item</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_items_path %>

app/views/ticket_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket_item.name %>
</p>

<p>
  <strong>Created on:</strong>
  <%= @ticket_item.created_on %>
</p>

<p>
  <strong>Assigned on:</strong>
  <%= @ticket_item.assigned_on %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket_item.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket_item.user_id %>
</p>

<%= link_to 'Edit', edit_ticket_item_path(@ticket_item) %> |
<%= link_to 'Back', ticket_items_path %>